In [1]:
import pandas as pd

In [2]:
!ls

filter.ipynb  SB11_20182.TXT

In [3]:
DATA = pd.read_csv("SB11_20182.TXT", sep="Â¬", engine="python")

In [9]:
DATA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549934 entries, 0 to 549933
Data columns (total 83 columns):
ESTU_TIPODOCUMENTO               549934 non-null object
ESTU_NACIONALIDAD                549934 non-null object
ESTU_GENERO                      549934 non-null object
ESTU_FECHANACIMIENTO             549934 non-null object
PERIODO                          549934 non-null int64
ESTU_CONSECUTIVO                 549934 non-null object
ESTU_ESTUDIANTE                  549934 non-null object
ESTU_PAIS_RESIDE                 549934 non-null object
ESTU_TIENEETNIA                  549798 non-null object
ESTU_ETNIA                       34975 non-null object
ESTU_LIMITA_MOTRIZ               1 non-null object
ESTU_DEPTO_RESIDE                549798 non-null object
ESTU_COD_RESIDE_DEPTO            549798 non-null float64
ESTU_MCPIO_RESIDE                549798 non-null object
ESTU_COD_RESIDE_MCPIO            549798 non-null float64
FAMI_ESTRATOVIVIENDA             510663 non-null object
FAMI_PERSONASHOGAR               531187 non-null object
FAMI_CUARTOSHOGAR                530179 non-null object
FAMI_EDUCACIONPADRE              514363 non-null object
FAMI_EDUCACIONMADRE              514554 non-null object
FAMI_TRABAJOLABORPADRE           528424 non-null object
FAMI_TRABAJOLABORMADRE           529466 non-null object
FAMI_TIENEINTERNET               514123 non-null object
FAMI_TIENESERVICIOTV             513002 non-null object
FAMI_TIENECOMPUTADOR             530470 non-null object
FAMI_TIENELAVADORA               530563 non-null object
FAMI_TIENEHORNOMICROOGAS         529700 non-null object
FAMI_TIENEAUTOMOVIL              529132 non-null object
FAMI_TIENEMOTOCICLETA            530170 non-null object
FAMI_TIENECONSOLAVIDEOJUEGOS     529128 non-null object
FAMI_NUMLIBROS                   500129 non-null object
FAMI_COMELECHEDERIVADOS          509129 non-null object
FAMI_COMECARNEPESCADOHUEVO       512541 non-null object
FAMI_COMECEREALFRUTOSLEGUMBRE    511557 non-null object
FAMI_SITUACIONECONOMICA          530435 non-null object
ESTU_DEDICACIONLECTURADIARIA     513346 non-null object
ESTU_DEDICACIONINTERNET          512022 non-null object
ESTU_HORASSEMANATRABAJA          530167 non-null object
ESTU_TIPOREMUNERACION            528688 non-null object
COLE_CODIGO_ICFES                549934 non-null int64
COLE_COD_DANE_ESTABLECIMIENTO    549934 non-null int64
COLE_NOMBRE_ESTABLECIMIENTO      549934 non-null object
COLE_GENERO                      549934 non-null object
COLE_NATURALEZA                  549934 non-null object
COLE_CALENDARIO                  549934 non-null object
COLE_BILINGUE                    466758 non-null object
COLE_CARACTER                    538132 non-null object
COLE_COD_DANE_SEDE               549934 non-null int64
COLE_NOMBRE_SEDE                 549934 non-null object
COLE_SEDE_PRINCIPAL              549934 non-null object
COLE_AREA_UBICACION              549934 non-null object
COLE_JORNADA                     549934 non-null object
COLE_COD_MCPIO_UBICACION         549934 non-null int64
COLE_MCPIO_UBICACION             549934 non-null object
COLE_COD_DEPTO_UBICACION         549934 non-null int64
COLE_DEPTO_UBICACION             549934 non-null object
ESTU_PRIVADO_LIBERTAD            549934 non-null object
ESTU_COD_MCPIO_PRESENTACION      549934 non-null int64
ESTU_MCPIO_PRESENTACION          549934 non-null object
ESTU_DEPTO_PRESENTACION          549934 non-null object
ESTU_COD_DEPTO_PRESENTACION      549934 non-null int64
PUNT_LECTURA_CRITICA             549934 non-null int64
PERCENTIL_LECTURA_CRITICA        549934 non-null int64
DESEMP_LECTURA_CRITICA           549934 non-null int64
PUNT_MATEMATICAS                 549934 non-null int64
PERCENTIL_MATEMATICAS            549934 non-null int64
DESEMP_MATEMATICAS               549934 non-null int64
PUNT_C_NATURALES                 549934 non-null int64
PERCENTIL_C_NATURALES            549934 non-null int64
DESEMP_C_NATURALES               549934 non-null int64
PUNT_SOCIALES_CIUDADANAS         549934 non-null int64
PERCENTIL_SOCIALES_CIUDADANAS    549934 non-null int64
DESEMP_SOCIALES_CIUDADANAS       549934 non-null int64
PUNT_INGLES                      549913 non-null float64
PERCENTIL_INGLES                 549934 non-null int64
DESEMP_INGLES                    549934 non-null object
PUNT_GLOBAL                      549934 non-null int64
PERCENTIL_GLOBAL                 549934 non-null int64
ESTU_NSE_ESTABLECIMIENTO         549357 non-null float64
ESTU_INSE_INDIVIDUAL             531707 non-null float64
ESTU_NSE_INDIVIDUAL              531707 non-null object
ESTU_ESTADOINVESTIGACION         549934 non-null object
ESTU_GENERACION-E                549934 non-null object
dtypes: float64(5), int64(23), object(55)
memory usage: 348.2+ MB

In [4]:
DATA

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_ETNIA,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,CR,COLOMBIA,M,22/09/1999,20182,SB11201820540351,ESTUDIANTE,COLOMBIA,No,NaN,...,42.0,25,A-,177,6,2.0,45.885859,NSE2,PUBLICAR,NO
1,TI,COLOMBIA,M,29/12/2000,20182,SB11201820059515,ESTUDIANTE,COLOMBIA,No,NaN,...,41.0,22,A-,199,16,1.0,37.079030,NSE1,PUBLICAR,GENERACION E - GRATUIDAD
2,CC,COLOMBIA,F,22/04/1998,20182,SB11201820568196,ESTUDIANTE,COLOMBIA,No,NaN,...,38.0,14,A-,180,7,2.0,45.303861,NSE2,PUBLICAR,GENERACION E - GRATUIDAD
3,TI,COLOMBIA,F,30/05/2002,20182,SB11201820446686,ESTUDIANTE,COLOMBIA,No,NaN,...,44.0,31,A-,253,54,2.0,43.189222,NSE2,PUBLICAR,GENERACION E - GRATUIDAD
4,TI,COLOMBIA,F,20/11/2000,20182,SB11201820454103,ESTUDIANTE,COLOMBIA,No,NaN,...,29.0,1,A-,202,18,2.0,51.743335,NSE3,PUBLICAR,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549929,TI,COLOMBIA,F,27/12/2001,20182,SB11201820508914,ESTUDIANTE,COLOMBIA,No,NaN,...,48.0,46,A1,294,79,3.0,50.814346,NSE2,PUBLICAR,GENERACION E - GRATUIDAD
549930,TI,COLOMBIA,F,20/04/2001,20182,SB11201820468953,ESTUDIANTE,COLOMBIA,No,NaN,...,48.0,44,A1,197,15,2.0,51.264289,NSE3,PUBLICAR,GENERACION E - GRATUIDAD
549931,TI,COLOMBIA,F,04/02/2001,20182,SB11201820315273,ESTUDIANTE,COLOMBIA,No,NaN,...,42.0,24,A-,264,62,2.0,37.863280,NSE1,PUBLICAR,GENERACION E - GRATUIDAD
549932,CC,COLOMBIA,F,18/02/1997,20182,SB11201820572423,ESTUDIANTE,COLOMBIA,No,NaN,...,32.0,3,A-,173,4,2.0,37.442275,NSE1,PUBLICAR,NO
549933,TI,COLOMBIA,F,06/03/2001,20182,SB11201820268692,ESTUDIANTE,COLOMBIA,No,NaN,...,50.0,52,A1,240,44,2.0,49.180568,NSE2,PUBLICAR,GENERACION E - GRATUIDAD

In [20]:
columns = ["ESTU_TIPODOCUMENTO",
           "ESTU_NACIONALIDAD",
           "ESTU_GENERO", 
           "ESTU_FECHANACIMIENTO", 
           "ESTU_CONSECUTIVO", 
           "ESTU_ETNIA", 
           "ESTU_DEPTO_RESIDE", 
           "ESTU_MCPIO_RESIDE", 
           "FAMI_ESTRATOVIVIENDA", 
           "FAMI_NUMLIBROS",
           "FAMI_SITUACIONECONOMICA", 
           "ESTU_DEDICACIONLECTURADIARIA", 
           "COLE_CODIGO_ICFES", 
           "COLE_NOMBRE_ESTABLECIMIENTO", 
           "COLE_GENERO", 
           "COLE_NATURALEZA", 
           "COLE_JORNADA", 
           "PUNT_LECTURA_CRITICA", 
           "PUNT_MATEMATICAS", 
           "PUNT_C_NATURALES", 
           "PUNT_SOCIALES_CIUDADANAS", 
           "PUNT_INGLES", 
           "DESEMP_INGLES", 
           "PUNT_GLOBAL", 
           "PERCENTIL_GLOBAL", 
           "ESTU_NSE_INDIVIDUAL"]

In [21]:
len(columns)

26

In [25]:
DATA[columns].to_csv("SB11_2018-2_modified.csv", index=False, sep=";")